### ISSUE TITLE
Exception on /addrec Post

### ISSUE THREAD

**Issue by RajVishwakarma69** [RekhaBhale/face-recognition#1]
IF YOU ARE REPORTING A BUG OR PROBLEM WITH DLIB THEN FILL OUT THE ENTIRE TEMPLATE BELOW.  ISSUES ASKING QUESTIONS ABOUT WHY SOMETHING DOESN'T WORK THAT FAIL TO FILL OUT THE ENTIRE TEMPLATE WILL BE CLOSED.

It is OK to suggest interesting improvements to dlib, even if you are not volunteering to implement them.  **However, the issue tracker is not a code writing service, do not ask for someone to write code for you.**  E.g. Do not ask for feature improvements to the example programs. **If there is some feature improvement you want in an example program then it's up to you to write it**.  

Before you ask a question, check Google for a solution, [the dlib FAQ](http://dlib.net/faq.html), or consult the dlib documentation.  Every single function in dlib is documented in detail.  If you obviously haven't read the documentation your issue will be closed.  

If you aren't reporting a bug or problem with dlib then delete this template and write whatever you want here.
 

## Steps to Reproduce

* **Version**: 
* **Where did you get dlib**: 
* **Platform**: 
* **Compiler**:

**Comment by RajVishwakarma69** [comment]
Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [27/Apr/2019 17:12:42] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Apr/2019 17:12:42] "GET /static/Plain-Light-Backgrounds.jpg HTTP/1.1" 404 -
127.0.0.1 - - [27/Apr/2019 17:25:12] "GET /reg1 HTTP/1.1" 200 -
aaaab
[2019-04-27 17:26:53,064] ERROR in app: Exception on /addrec [POST]
Traceback (most recent call last):
  File "C:\Users\rajvi\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rajvi\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rajvi\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\rajvi\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\rajvi\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rajvi\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\rajvi\Desktop\face-recognition-master\app.py", line 84, in addrec
    pass_police = test(str(head_pass1))
  File "C:\Users\rajvi\Desktop\face-recognition-master\md5.py", line 269, in test
    return md5(input).hexdigest()
  File "C:\Users\rajvi\Desktop\face-recognition-master\md5.py", line 142, in hexdigest
    return self.digest().encode("hex")
  File "C:\Users\rajvi\Desktop\face-recognition-master\md5.py", line 133, in digest
    self.update(padding(self.count))
  File "C:\Users\rajvi\Desktop\face-recognition-master\md5.py", line 160, in padding
    return PADDING[:padLen] + _encode((msg_bits & 0xffffffff, msg_bits >> 32), 8)
  File "C:\Users\rajvi\Desktop\face-recognition-master\md5.py", line 254, in _encode
    res = PIL._imagingmorph.apply(struct.pack, ("%iI" % k,) + tuple(input[:k]))
RuntimeError: Argument parsing problem

**Comment by RajVishwakarma69** [comment]
i have try to execute as example add police sign up then getting the exception what's the going wrong....
